# Generated by Django 3.2.6 on 2021-10-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_genre',
            field=models.CharField(choices=[('Mystery/Thriller', 'Mystery/Thriller'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Documentary', 'Documentary')], default='Random', max_length=75),
        ),
    ]
