# Generated by Django 3.2.6 on 2021-10-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie_yor',
            new_name='movie_YearOfRelease',
        ),
    ]
